# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MC_int_xy_all_cpp <- function(s_i, y_i, mu_tte, sd_tte, mu_y, sigma_y_sq, mu_r, sigma_r, sample_J, x_min, obs = FALSE) {
    .Call(`_MCEMCRJointCPP_MC_int_xy_all_cpp`, s_i, y_i, mu_tte, sd_tte, mu_y, sigma_y_sq, mu_r, sigma_r, sample_J, x_min, obs)
}

g_0_cpp <- function(t, mu_omega, sigma_omega) {
    .Call(`_MCEMCRJointCPP_g_0_cpp`, t, mu_omega, sigma_omega)
}

g_1_cpp <- function(t, mu_omega, sigma_omega) {
    .Call(`_MCEMCRJointCPP_g_1_cpp`, t, mu_omega, sigma_omega)
}

g_2_cpp <- function(t, mu_omega, sigma_omega) {
    .Call(`_MCEMCRJointCPP_g_2_cpp`, t, mu_omega, sigma_omega)
}

Z_i_cpp <- function(y, visittime_vec_i) {
    .Call(`_MCEMCRJointCPP_Z_i_cpp`, y, visittime_vec_i)
}

Mahalanobis <- function(x, center, cov) {
    .Call(`_MCEMCRJointCPP_Mahalanobis`, x, center, cov)
}

dmvnorm_arma <- function(x, mean, sigma, log) {
    .Call(`_MCEMCRJointCPP_dmvnorm_arma`, x, mean, sigma, log)
}

rcpp_hello <- function() {
    .Call(`_MCEMCRJointCPP_rcpp_hello`)
}

rtruncnorm_cpp <- function(n, a, b, mean, sd) {
    .Call(`_MCEMCRJointCPP_rtruncnorm_cpp`, n, a, b, mean, sd)
}

